<template>
  <div>
    <h2>Accordion</h2>
    <p>Accordions are used to toggle sections of content.</p>

    <h3>Basic use</h3>
    <accordion :items="items" icon="icon-arrow-right">
      <span slot="header" slot-scope="{ item: { value: { title } } }">{{ title }}</span>
      <span slot="body" slot-scope="{ item: { value: { text } } }">{{ text }}</span>
    </accordion>

    <prism language="html" :code="htmlCode" />
    <prism language="javascript" :code="jsCode" />

    <h3>Multiple</h3>
    <accordion :items="items" multiple>
      <span slot="header" slot-scope="{ item: { value: { title } } }">{{ title }}</span>
      <span slot-scope="{ item: { value: { text } } }">{{ text }}</span>
    </accordion>
    <prism language="html" :code="multipleHtml" />

    <props-list :props="accordionProps" />
    <slots-list :slots="accordionSlots" />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { IconNavigation } from "../../../../src/components";

import Props from "../../../component/Props";
import { PropDefinitions } from "../../../component/Props/defs";
import Slots from "../../../component/Slots";
import { SlotDefinitions } from "../../../component/Slots/defs";

export default Vue.extend({
  components: {
    propsList: Props,
    slotsList: Slots,
  },
  data: () => ({
    icon: IconNavigation.right,
    accordionProps: <PropDefinitions> {
      items: { required: true, type: 'Any[]', description: 'shown items' },
      checked: { type: 'Number[], String[], Number, String' },
      name: { type: 'String', description: 'used as id, randomly generated by default' },
      multiple: { type: 'Boolean', description: 'show multiple items at once', default: false },
      icon: { type: 'String' }
    },
    accordionSlots: <SlotDefinitions> {
      header: {},
      body: {},
      default: {},
    },
    htmlCode: `
<accordion :items="items" icon="icon-arrow-right">
  <span slot="header" slot-scope="{ item: { value: { title } } }">{{ title }}</span>
  <span slot="body" slot-scope="{ item: { value: { text } } }">{{ text }}</span>
</accordion>
    `,
    multipleHtml: `
<accordion :items="items" multiple>
    `,
    jsCode: `
import Vue from 'vue';
import { Accordion } from 'vectre';

export default Vue.extend({
  components: {
    Accordion,
  },
  data: () => ({
    items: [
      {
        title: "Elements",
        text: "Text about elements"
      },
      {
        text: "Layout 1",
        title: "Layout"
      },
      {
        text: "Components 1",
        title: "Components"
      }
    ]
  })
});
      `,
    items: [
      {
        title: "Elements",
        text: "Text about elements"
      },
      {
        text: "Layout 1",
        title: "Layout"
      },
      {
        text: "Components 1",
        title: "Components"
      }
    ]
  })
});
</script>
