import * as tsx from 'vue-tsx-support';
export declare const Empty: import("vue").VueConstructor<{
    _tsxattrs: tsx.TsxComponentAttrs<{} & {
        icon?: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
        title?: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
        sub?: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
    }, {}, {}>;
} & import("vue").default & {
    icon: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
    title: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
    sub: "hResize" | "vResize" | "plus" | "minus" | "cross" | "check" | "stop" | "shutdown" | "refresh" | "search" | "flag" | "bookmark" | "edit" | "delete" | "share" | "download" | "upload" | "mail" | "people" | "message" | "photo" | "time" | "location" | "link" | "emoji" | "up" | "down" | "right" | "left" | "upward" | "forward" | "downward" | "back" | "caret" | "menu" | "apps" | "hMore" | "vMore";
}>;
